### ISSUE TITLE
navicat 连接文档不对

### ISSUE THREAD

**Issue by florashi181** [matrixorigin/moc-docs#192]
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/App-Develop/connect-mo/database-client-tools/
<img width="634" alt="image" src="https://github.com/matrixone-cloud/moc-docs/assets/87641339/b4db7fe1-1bfe-45ab-937c-b579fb954db1">
==这里的host、user等，应该都是实际连接串中的内容，不是固定的，截图也不对

**Comment by cyann7** [comment]
mysql -h moc.cluster.matrixonecloud.cn -P 6001 -u a123456b_78cd_9e12_fg34_abcd5d6789ef:admin:accountadmin  -p

**Comment by dengn** [comment]
host地址现在不是这个了，版本也更新了

<img width="769" alt="image" src="https://github.com/matrixone-cloud/moc-docs/assets/4965857/3d310112-a9e6-43a4-801c-07fefa06d156">

<img width="970" alt="image" src="https://github.com/matrixone-cloud/moc-docs/assets/4965857/bb735acb-ecf0-4054-a1d6-bc9593e3ba51">

@yangj1211 please update.
