### ISSUE TITLE
MO Cloud中测试看到只支持在阿里云上创建数据库实例

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/moc-docs#51]
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/Overview/matrixonecloud-introduction/

原文内容：MO Cloud 目前支持在 Amazon Web Services (AWS) 和阿里云上创建数据库实例。

测试时看到当前仅可选阿里云：
![image](https://github.com/matrixone-cloud/moc-docs/assets/90299197/7319badf-e63b-4cc8-8bcb-be7636efc011)

**Comment by dengn** [comment]
修正一下描述 @yangj1211

**Comment by johnwills72** [comment]
Thanks for the update! It's good to know that database instances creation on Alibaba Cloud is supported in MO Cloud testing. This could provide valuable options for users seeking database solutions to the [Photo call tv](https://photocall-tv.com/). Looking forward to further developments in this area.
