### ISSUE TITLE
申请试用MO Cloud时只支持使用邮箱注册

### ISSUE THREAD

**Issue by WuMenglong** [matrixorigin/moc-docs#58]
https://docs.matrixorigin.cn/zh/matrixonecloud/MatrixOne-Cloud/Get-Started/quickstart/

文中提到：
使用以下方式注册 MO Cloud 账户：电子邮箱账户、Github 账户、Google 账户。

当前仅支持使用邮箱，建议删除文中“申请试用 MO Cloud”章节提到的其他注册方式以及后面关于“第三方账户注册”的一小段，同时，删除“登录 MO Cloud 账户”中关于“第三方账号注册”的一小段。

**Comment by dengn** [comment]
现在没有Github 账户、Google 账户注册方式。删掉。@yangj1211
